---
Profiles:

    EfiOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererEfi
        Consortiums:
            EfiConsortium:
                Organizations:
                    - *Mother
                    - *MediaMarkt
                    - *Aldi
    EfiChannel:
        Consortium: EfiConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Mother
                - *MediaMarkt
                - *Aldi

Organizations:

    - &OrdererEfi
        Name: OrdererEfi

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/efi.com/msp

    - &Mother
        Name: MotherMSP

        ID: MotherMSP

        MSPDir: crypto-config/peerOrganizations/mother.efi.com/msp

        AnchorPeers:
            - Host: peer0.mother.efi.com
              Port: 7051

    - &MediaMarkt
        Name: MediaMarktMSP

        ID: MediaMarktMSP

        MSPDir: crypto-config/peerOrganizations/mediamarkt.efi.com/msp

        AnchorPeers:
            - Host: peer0.mediamarkt.efi.com
              Port: 7051

    - &Aldi
        Name: AldiMSP

        ID: AldiMSP

        MSPDir: crypto-config/peerOrganizations/aldi.efi.com/msp

        AnchorPeers:
            - Host: peer0.aldi.efi.com
              Port: 7051

Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.efi.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

Application: &ApplicationDefaults

    Organizations:
