OrdererOrgs:
  - Name: Orderer
    Domain: efi.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Mother
    Domain: mother.efi.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: MediaMarkt
    Domain: mediamarkt.efi.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Aldi
    Domain: aldi.efi.com
    Template:
      Count: 1
    Users:
      Count: 1
