version: '2'

networks:
  basic:

services:
  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-mother
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mother.efi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/60ae14c5b8253d521134dcca5b2bd99b035404804115cab3acbf3e912af6b046_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.mother.efi.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/60ae14c5b8253d521134dcca5b2bd99b035404804115cab3acbf3e912af6b046_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/mother.efi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMother
    networks:
      - basic

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-mediamarkt
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mediamarkt.efi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/22aa2557b09c54884c12879d92f41ac5be416ab50298fd9300f4eb906cbcc3c8_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.mediamarkt.efi.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/22aa2557b09c54884c12879d92f41ac5be416ab50298fd9300f4eb906cbcc3c8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/mediamarkt.efi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerMediaMarkt
    networks:
      - basic

  ca2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-aldi
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.aldi.efi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/363b541dace6bb99927a508ee8091e88e993f12cfa86819bb97c3b99e077e5f6_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.aldi.efi.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/363b541dace6bb99927a508ee8091e88e993f12cfa86819bb97c3b99e077e5f6_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/aldi.efi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerAldi
    networks:
      - basic

  orderer.efi.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.efi.com
    container_name: orderer.efi.com
    networks:
      - basic

  peer0.mother.efi.com:
    container_name: peer0.mother.efi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.mother.efi.com
    networks:
      - basic

  peer0.mediamarkt.efi.com:
    container_name: peer0.mediamarkt.efi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.mediamarkt.efi.com
    networks:
      - basic

  peer0.aldi.efi.com:
    container_name: peer0.aldi.efi.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.aldi.efi.com
    networks:
      - basic

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 5984:5984
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.mother.efi.com:7051
      - CORE_PEER_LOCALMSPID=MotherMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mother.efi.com/peers/peer0.mother.efi.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mother.efi.com/peers/peer0.mother.efi.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mother.efi.com/peers/peer0.mother.efi.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mother.efi.com/users/Admin@mother.efi.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.efi.com
      - peer0.mother.efi.com
      - peer0.mediamarkt.efi.com
      - peer0.aldi.efi.com
    networks:
      - basic
