version: '2'

services:

  orderer.efi.com:
    container_name: orderer.efi.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/efi.com/orderers/orderer.efi.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/efi.com/orderers/orderer.efi.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  peer0.mother.efi.com:
    container_name: peer0.mother.efi.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mother.efi.com
      - CORE_PEER_ADDRESS=peer0.mother.efi.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mother.efi.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.mother.efi.com:7051
      - CORE_PEER_LOCALMSPID=MotherMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/mother.efi.com/peers/peer0.mother.efi.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/mother.efi.com/peers/peer0.mother.efi.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer0.mediamarkt.efi.com:
    container_name: peer0.mediamarkt.efi.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mediamarkt.efi.com
      - CORE_PEER_ADDRESS=peer0.mediamarkt.efi.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mediamarkt.efi.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.mediamarkt.efi.com:7051
      - CORE_PEER_LOCALMSPID=MediaMarktMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/mediamarkt.efi.com/peers/peer0.mediamarkt.efi.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/mediamarkt.efi.com/peers/peer0.mediamarkt.efi.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  peer0.aldi.efi.com:
    container_name: peer0.aldi.efi.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.aldi.efi.com
      - CORE_PEER_ADDRESS=peer0.aldi.efi.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.aldi.efi.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.aldi.efi.com:7051
      - CORE_PEER_LOCALMSPID=AldiMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/aldi.efi.com/peers/peer0.aldi.efi.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/aldi.efi.com/peers/peer0.aldi.efi.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053
